import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Yusuf Wandana | Full-Stack Developer</title>
        <meta
          name="description"
          content="Personal Portofolio of Yusuf Wandana, Full-Stack Developer"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function() {
              try {
                var theme = localStorage.getItem('theme');
                var systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                var initialTheme = theme || systemTheme;
                document.documentElement.className = initialTheme;
              } catch (e) {}
            })();
          `,
          }}
        />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
